trigger: none

pool:
  name: 'Default'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'install -g nx'
    displayName: 'NPM - Install NX CLI'

  - task: Npm@1
    inputs:
      command: 'install'
    displayName: "NPM - Install Dependencies"

  - script: |
      nx run frontend:build --skip-nx-cache
    displayName: 'Angular - Build Frontend Project'

  - script: |
      nx run electron:build --skip-nx-cache
    displayName: 'Electron - Build Project'

  - script: |
      nx run electron:make --skip-nx-cache
    displayName: 'Electron - Make Project'

  - script: |
      nx run-many --target=lint --all --skip-nx-cache
    displayName: 'ESLint - Lint Workspace'
